0 config pair_secret=default_web
0 config m=0
0 config wifi.ssid=aaaa&wifi.password=xyz
0 config tsinaddr=01-FD-7D-45-38-FC-89-40&tsoutaddr=02-6D-38-D9-78-EF-00-1E
0 temp_set 20 20
+1 config tray.bgfc = 0
+1 config tray.f1kgt = 266
+1 config m=1
+800 temp_smooth 25 41
+200 temp_smooth 35 36
+800 temp_smooth 62 75
+100 temp_smooth 62 80
+200 temp_smooth 59 70
+800 temp_smooth 62 90

+1000 tray_open