#pragma once
namespace DotMatrix {

constexpr auto font_6p = FontP<7, 6>({FontFaceP<7, 6>
   { 4, "      "
        "      "
        "      "
        "      "
        "      "
        "      "
        "      " },
   { 2, "x     "
        "x     "
        "x     "
        "x     "
        "      "
        "x     "
        "      " },
   { 4, "x x   "
        "x x   "
        "      "
        "      "
        "      "
        "      "
        "      " },
   { 6, "      "
        " x x  "
        "xxxxx "
        " x x  "
        "xxxxx "
        " x x  "
        "      " },
   { 6, "  x   "
        "xxxxx "
        "x x   "
        "xxxxx "
        "  x x "
        "xxxxx "
        "  x   " },
    { 6, "xx    "
         "xx  x "
         "   x  "
         "  x   "
         " x    "
         "x  xx "
         "   xx " },
   { 6, " x    "
        "x x   "
        "x x   "
        " xx x "
        "x  x  "
        "xxx x "
        "      " },
   { 2, "x     "
        "x     "
        "      "
        "      "
        "      "
        "      "
        "      " },
   { 3, " x    "
        "x     "
        "x     "
        "x     "
        "x     "
        " x    "
        "      " },
   { 3, "x     "
        " x    "
        " x    "
        " x    "
        " x    "
        "x     "
        "      " },
   { 6, "      "
        " x x  "
        "  x   "
        "xxxxx "
        "  x   "
        " x x  "
        "      " },
   { 6, "      "
        "  x   "
        "  x   "
        "xxxxx "
        "  x   "
        "  x   "
        "      " },
   { 3, "      "
        "      "
        "      "
        "      "
        " x    "
        " x    "
        "x     " },
   { 6, "      "
        "      "
        "      "
        "xxxxx "
        "      "
        "      "
        "      " },
   { 2, "      "
        "      "
        "      "
        "      "
        "      "
        "x     "
        "      " },
   { 4, "  x   "
        "  x   "
        " x    "
        " x    "
        "x     "
        "x     "
        "      " },
   { 5, " xx   "
        "x  x  "
        "x  x  "
        "x  x  "
        "x  x  "
        " xx   "
        "      " },
   { 5, "  x   "
        " xx   "
        "x x   "
        "  x   "
        "  x   "
        "  x   "
        "      " },
   { 5, " xx   "
        "x  x  "
        "   x  "
        " xx   "
        "x     "
        "xxxx  "
        "      " },
   { 5, " xx   "
        "x  x  "
        "  x   "
        "   x  "
        "x  x  "
        " xx   "
        "      " },
   { 5, "  x   "
        " xx   "
        "x x   "
        "xxxx  "
        "  x   "
        "  x   "
        "      " },
   { 5, "xxxx  "
        "x     "
        "xxx   "
        "   x  "
        "x  x  "
        " xx   "
        "      " },
   { 5, " xx   "
        "x     "
        "xxx   "
        "x  x  "
        "x  x  "
        " xx   "
        "      " },
   { 5, "xxxx  "
        "   x  "
        "  x   "
        " x    "
        " x    "
        " x    "
        "      " },
   { 5, " xx   "
        "x  x  "
        " xx   "
        "x  x  "
        "x  x  "
        " xx   "
        "      " },
   { 5, " xx   "
        "x  x  "
        "x  x  "
        " xxx  "
        "   x  "
        " xx   "
        "      " },
   { 2, "      "
        "      "
        "      "
        "x     "
        "      "
        "x     "
        "      " },
   { 3, "      "
        "      "
        "      "
        " x    "
        "      "
        " x    "
        "x     " },
   { 4, "      "
        "  x   "
        " x    "
        "x     "
        " x    "
        "  x   "
        "      " },
   { 4, "      "
        "      "
        "xxx   "
        "      "
        "xxx   "
        "      "
        "      " },
    {4, "      "
        "x     "
        " x    "
        "  x   "
        " x    "
        "x     "
        "      " },
   { 5, " xx   "
        "x  x  "
        "   x  "
        "  x   "
        "      "
        "  x   "
        "      " },
   { 7, "  xxx "
        " x   x"
        "x  x x"
        "x x xx"
        "x  x x"
        " x    "
        "  xxxx" },
   { 5, " xx   "
        "x  x  "
        "x  x  "
        "xxxx  "
        "x  x  "
        "x  x  "
        "      " },
   { 5, "xxx   "
        "x  x  "
        "xxx   "
        "x  x  "
        "x  x  "
        "xxx   "
        "      " },
   { 5, " xx   "
        "x  x  "
        "x     "
        "x     "
        "x  x  "
        " xx   "
        "      " },
   { 5, "xx    "
        "x x   "
        "x  x  "
        "x  x  "
        "x x   "
        "xx    "
        "      " },
   { 5, "xxxx  "
        "x     "
        "xx    "
        "x     "
        "x     "
        "xxxx  "
        "      " },
   { 5, "xxxx  "
        "x     "
        "xx    "
        "x     "
        "x     "
        "x     "
        "      " },
   { 5, " xx   "
        "x  x  "
        "x     "
        "x xx  "
        "x  x  "
        " xx   "
        "      " },
   { 5, "x  x  "
        "x  x  "
        "xxxx  "
        "x  x  "
        "x  x  "
        "x  x  "
        "      " },
   { 4, "xxx   "
        " x    "
        " x    "
        " x    "
        " x    "
        "xxx   "
        "      " },
   { 5, " xxx  "
        "   x  "
        "   x  "
        "   x  "
        "x  x  "
        " xx   "
        "      " },
   { 5, "x  x  "
        "x x   "
        "xx    "
        "x x   "
        "x  x  "
        "x  x  "
        "      " },
   { 5, "x     "
        "x     "
        "x     "
        "x     "
        "x     "
        "xxxx  "
        "      " },
   { 6, "x   x "
        "xx xx "
        "x x x "
        "x   x "
        "x   x "
        "x   x "
        "      " },
   { 5, "x  x  "
        "xx x  "
        "xx x  "
        "x xx  "
        "x xx  "
        "x  x  "
        "      " },
   { 5, " xx   "
        "x  x  "
        "x  x  "
        "x  x  "
        "x  x  "
        " xx   "
        "      " },
   { 5, "xxx   "
        "x  x  "
        "x  x  "
        "xxx   "
        "x     "
        "x     "
        "      " },
   { 5, " xx   "
        "x  x  "
        "x  x  "
        "x  x  "
        "x xx  "
        " xxx  "
        "      " },
   { 5, "xxx   "
        "x  x  "
        "x  x  "
        "xxx   "
        "x  x  "
        "x  x  "
        "      " },
   { 5, " xx   "
        "x     "
        " xx   "
        "   x  "
        "x  x  "
        " xx   "
        "      " },
   { 6, "xxxxx "
        "  x   "
        "  x   "
        "  x   "
        "  x   "
        "  x   "
        "      " },
   { 5, "x  x  "
        "x  x  "
        "x  x  "
        "x  x  "
        "x  x  "
        " xx   "
        "      " },
   { 6, "x   x "
        "x   x "
        "x   x "
        "x   x "
        " x x  "
        "  x   "
        "      " },
   { 6, "x   x "
        "x   x "
        "x   x "
        "x x x "
        "x x x "
        " x x  "
        "      " },
   { 5, "x  x  "
        "x  x  "
        " xx   "
        " xx   "
        "x  x  "
        "x  x  "
        "      " },
   { 6, "x   x "
        "x   x "
        " x x  "
        "  x   "
        "  x   "
        "  x   "
        "      " },
   { 5, "xxxx  "
        "   x  "
        "  x   "
        " x    "
        "x     "
        "xxxx  "
        "      " },
   { 3, "xx    "
        "x     "
        "x     "
        "x     "
        "x     "
        "xx    "
        "      " },
   { 5, "      "
        "x     "
        " x    "
        "  x   "
        "   x  "
        "      "
        "      " },
   { 3, "xx    "
        " x    "
        " x    "
        " x    "
        " x    "
        "xx    "
        "      " },
   { 6, "  x   "
        " xxx  "
        "x x x "
        "  x   "
        "  x   "
        "  x   "
        "      " },
   { 5, "      "
        "      "
        "      "
        "      "
        "      "
        "      "
        "xxxxx " },
   { 3, "x     "
        " x    "
        "      "
        "      "
        "      "
        "      "
        "      " },
   { 5, "      "
        "      "
        " xx   "
        "  xx  "
        "xx x  "
        " xxx  "
        "      " },
   { 5, "x     "
        "x     "
        "xxx   "
        "x  x  "
        "x  x  "
        "xxx   "
        "      " },
   { 5, "      "
        "      "
        " xxx  "
        "x     "
        "x     "
        " xxx  "
        "      " },
   { 5, "   x  "
        "   x  "
        " xxx  "
        "x  x  "
        "x  x  "
        " xxx  "
        "      " },
   { 5, "      "
        "      "
        " xx   "
        "x xx  "
        "xx    "
        " xxx  "
        "      " },
   { 4, "  x   "
        " x    "
        "xxx   "
        " x    "
        " x    "
        " x    "
        "      " },
   { 5, "      "
        "      "
        " xxx  "
        "x  x  "
        " xxx  "
        "   x  "
        " xx   " },
   { 5, "x     "
        "x     "
        "xxx   "
        "x  x  "
        "x  x  "
        "x  x  "
        "      " },
   { 3, " x    "
        "      "
        "xx    "
        " x    "
        " x    "
        "xxx   "
        "      " },
   { 4, "  x   "
        "      "
        " xx   "
        "  x   "
        "  x   "
        "  x   "
        "xx    " },
   { 5, "x     "
        "x     "
        "x x   "
        "xx    "
        "x x   "
        "x  x  "
        "      " },
   { 3, "x     "
        "x     "
        "x     "
        "x     "
        "x     "
        " x    "
        "      " },
   { 6, "      "
        "      "
        "xxxx  "
        "x x x "
        "x x x "
        "x x x "
        "      " },
   { 5, "      "
        "      "
        "xxx   "
        "x  x  "
        "x  x  "
        "x  x  "
        "      " },
   { 5, "      "
        "      "
        " xx   "
        "x  x  "
        "x  x  "
        " xx   "
        "      " },
   { 5, "      "
        "      "
        "xxx   "
        "x  x  "
        "xxx   "
        "x     "
        "x     " },
   { 6, "      "
        "      "
        " xxx  "
        "x  x  "
        " xxx  "
        "   x  "
        "   xx " },
   { 5, "      "
        "      "
        " xxx  "
        "x     "
        "x     "
        "x     "
        "      " },
   { 5, "      "
        "      "
        " xx   "
        "xx    "
        "  xx  "
        "xxx   "
        "      " },
   { 4, " x    "
        "xxx   "
        " x    "
        " x    "
        " x    "
        "  x   "
        "      " },
   { 6, "      "
        "      "
        "x  x  "
        "x  x  "
        "x  x  "
        " xx   "
        "      " },
   { 6, "      "
        "      "
        "x   x "
        "x   x "
        " x x  "
        "  x   "
        "      " },
   { 6, "      "
        "      "
        "x   x "
        "x x x "
        "x x x "
        " x x  "
        "      " },
   { 5, "      "
        "      "
        "x  x  "
        " xx   "
        " xx   "
        "x  x  "
        "      " },
   { 5, "      "
        "      "
        "x  x  "
        "x  x  "
        " xxx  "
        "   x  "
        " xx   " },
   { 5, "      "
        "      "
        "xxxx  "
        "  x   "
        " x    "
        "xxxx  "
        "      " },
   { 4, " xx   "
        " x    "
        "xx    "
        " x    "
        " x    "
        " xx   "
        "      " },
   { 2, "x     "
        "x     "
        "x     "
        "x     "
        "x     "
        "x     "
        "      " },
   { 4, "xx    "
        " x    "
        " xx   "
        " x    "
        " x    "
        "xx    "
        "      " },
   { 6, "      "
        " x    "
        "x x x "
        "   x  "
        "      "
        "      "
        "      " },
   { 6, "      "
        "  x   "
        "  x   "
        "  x   "
        "x x x "
        " xxx  "
        "  x   " }

});

}
