#pragma once
namespace DotMatrix {
constexpr Font<6,4> font_5x3 ({
        "    "
        "    "
        "    "
        "    "
        "    "
        "    ",
        " X  "
        " X  "
        " X  "
        "    "
        " X  "
        "    ",
        "X X "
        "X X "
        "    "
        "    "
        "    "
        "    ",
        "X X "
        "XXX "
        "X X "
        "XXX "
        "X X "
        "    ",
        "XXX "
        "XX  "
        "XXX "
        " XX "
        "XXX "
        "    ",
        "X X "
        "  X "
        " X  "
        "X   "
        "X X "
        "    ",
        " O  "
        "O O "
        " O  "
        "O  O"
        "OOO "
        "    ",
        " X  "
        " X  "
        "    "
        "    "
        "    "
        "    ",
        "  X "
        " X  "
        " X  "
        " X  "
        "  X "
        "    ",
        "X   "
        " X  "
        " X  "
        " X  "
        "X   "
        "    ",
        "    "
        "X X "
        " X  "
        "X X "
        "    "
        "    ",
        "    "
        " X  "
        "XXX "
        " X  "
        "    "
        "    ",
        "    "
        "    "
        "    "
        " X  "
        " X  "
        "X   ",
        "    "
        "    "
        "XXX "
        "    "
        "    "
        "    ",
        "    "
        "    "
        "    "
        "    "
        " X  "
        "    ",
        "    "
        "  X "
        " X  "
        "X   "
        "    "
        "    ",
        "XXX "
        "X X "
        "X X "
        "X X "
        "XXX "
        "    ",
        "  X "
        "  X "
        "  X "
        "  X "
        "  X "
        "    ",
        "XXX "
        "  X "
        "XXX "
        "X   "
        "XXX "
        "    ",
        "XXX "
        "  X "
        "XXX "
        "  X "
        "XXX "
        "    ",
        "X X "
        "X X "
        "XXX "
        "  X "
        "  X "
        "    ",
        "XXX "
        "X   "
        "XXX "
        "  X "
        "XXX "
        "    ",
        "XXX "
        "X   "
        "XXX "
        "X X "
        "XXX "
        "    ",
        "XXX "
        "  X "
        "  X "
        "  X "
        "  X "
        "    ",
        "XXX "
        "X X "
        "XXX "
        "X X "
        "XXX "
        "    ",
        "XXX "
        "X X "
        "XXX "
        "  X "
        "XXX "
        "    ",
        "    "
        " X  "
        "    "
        " X  "
        "    "
        "    ",
        "    "
        " X  "
        "    "
        " X  "
        " X  "
        "X   ",
        "  X "
        " X  "
        "X   "
        " X  "
        "  X "
        "    ",
        "    "
        "XXX "
        "    "
        "XXX "
        "    "
        "    ",
        "X   "
        " X  "
        "  X "
        " X  "
        "X   "
        "    ",
        "XX  "
        "  X "
        " X  "
        "    "
        " X  "
        "    ",
        " XX "
        "X  X"
        "XXXX"
        "XX X"
        " XX "
        "    ",
        " X  "
        "X X "
        "XXX "
        "X X "
        "X X "
        "    ",
        "XX  "
        "X X "
        "XX  "
        "X X "
        "XX  "
        "    ",
        " XX "
        "X   "
        "X   "
        "X   "
        " XX "
        "    ",
        "XX  "
        "X X "
        "X X "
        "X X "
        "XX  "
        "    ",
        "XXX "
        "X   "
        "XX  "
        "X   "
        "XXX "
        "    ",
        "XXX "
        "X   "
        "XX  "
        "X   "
        "X   "
        "    ",
        " XX "
        "X   "
        "X X "
        "X X "
        " XX "
        "    ",
        "X X "
        "X X "
        "XXX "
        "X X "
        "X X "
        "    ",
        "XXX "
        " X  "
        " X  "
        " X  "
        "XXX "
        "    ",
        "XXX "
        "  X "
        "  X "
        "X X "
        " X  "
        "    ",
        "X X "
        "X X "
        "XX  "
        "X X "
        "X X "
        "    ",
        "X   "
        "X   "
        "X   "
        "X   "
        "XXX "
        "    ",
        "X X "
        "XXX "
        "XXX "
        "X X "
        "X X "
        "    ",
        "XX  "
        "X X "
        "X X "
        "X X "
        "X X "
        "    ",
        " X  "
        "X X "
        "X X "
        "X X "
        " X  "
        "    ",
        "XX  "
        "X X "
        "XXX "
        "X   "
        "X   "
        "    ",
        " X  "
        "X X "
        "X X "
        "XXX "
        " XX "
        "    ",
        "XX  "
        "X X "
        "XX  "
        "X X "
        "X X "
        "    ",
        " XX "
        "X   "
        " X  "
        "  X "
        "XX  "
        "    ",
        "XXX "
        " X  "
        " X  "
        " X  "
        " X  "
        "    ",
        "X X "
        "X X "
        "X X "
        "X X "
        "XXX "
        "    ",
        "X X "
        "X X "
        "X X "
        "X X "
        " X  "
        "    ",
        "X X "
        "X X "
        "XXX "
        "XXX "
        " X  "
        "    ",
        "X X "
        "X X "
        " X  "
        "X X "
        "X X "
        "    ",
        "X X "
        "X X "
        " X  "
        " X  "
        " X  "
        "    ",
        "XXX "
        "  X "
        " X  "
        "X   "
        "XXX "
        "    ",
        " XX "
        " X  "
        " X  "
        " X  "
        " XX "
        "    ",
        "    "
        "X   "
        " X  "
        "  X "
        "    "
        "    ",
        "XX  "
        " X  "
        " X  "
        " X  "
        "XX  "
        "    ",
        " X  "
        "X X "
        "    "
        "    "
        "    "
        "    ",
        "    "
        "    "
        "    "
        "    "
        "    "
        "XXXX",
        " X  "
        "  X "
        "    "
        "    "
        "    "
        "    ",
        " X  "
        "X X "
        "XXX "
        "X X "
        "X X "
        "    ",
        "XX  "
        "X X "
        "XX  "
        "X X "
        "XX  "
        "    ",
        " XX "
        "X   "
        "X   "
        "X   "
        " XX "
        "    ",
        "XX  "
        "X X "
        "X X "
        "X X "
        "XX  "
        "    ",
        "XXX "
        "X   "
        "XX  "
        "X   "
        "XXX "
        "    ",
        "XXX "
        "X   "
        "XX  "
        "X   "
        "X   "
        "    ",
        " XX "
        "X   "
        "X X "
        "X X "
        " XX "
        "    ",
        "X X "
        "X X "
        "XXX "
        "X X "
        "X X "
        "    ",
        "XXX "
        " X  "
        " X  "
        " X  "
        "XXX "
        "    ",
        "XXX "
        "  X "
        "  X "
        "X X "
        " X  "
        "    ",
        "X X "
        "X X "
        "XX  "
        "X X "
        "X X "
        "    ",
        "X   "
        "X   "
        "X   "
        "X   "
        "XXX "
        "    ",
        "X X "
        "XXX "
        "XXX "
        "X X "
        "X X "
        "    ",
        "XX  "
        "X X "
        "X X "
        "X X "
        "X X "
        "    ",
        " X  "
        "X X "
        "X X "
        "X X "
        " X  "
        "    ",
        "XX  "
        "X X "
        "XXX "
        "X   "
        "X   "
        "    ",
        " X  "
        "X X "
        "X X "
        "XXX "
        " XX "
        "    ",
        "XX  "
        "X X "
        "XX  "
        "X X "
        "X X "
        "    ",
        " XX "
        "X   "
        " X  "
        "  X "
        "XX  "
        "    ",
        "XXX "
        " X  "
        " X  "
        " X  "
        " X  "
        "    ",
        "X X "
        "X X "
        "X X "
        "X X "
        "XXX "
        "    ",
        "X X "
        "X X "
        "X X "
        "X X "
        " X  "
        "    ",
        "X X "
        "X X "
        "XXX "
        "XXX "
        " X  "
        "    ",
        "X X "
        "X X "
        " X  "
        "X X "
        "X X "
        "    ",
        "X X "
        "X X "
        " X  "
        " X  "
        " X  "
        "    ",
        "XXX "
        "  X "
        " X  "
        "X   "
        "XXX "
        "    ",
        " XX "
        " X  "
        "X   "
        " X  "
        " XX "
        "    ",
        " X  "
        " X  "
        " X  "
        " X  "
        " X  "
        "    ",
        "XX  "
        " X  "
        "  X "
        " X  "
        "XX  "
        "    ",
        " X X"
        "X X "
        "    "
        "    "
        "    "
        "    ",
        "  X "
        " X  "
        "XXXX"
        " X  "
        "  X "
        "    ",
});

}
