#pragma once

#include "../includes/font.h"

#ifdef __AVR__
#include <avr/pgmspace.h>
#else
#define PROGMEM
#endif

namespace Matrix_MAX7219 {


constexpr auto PROGMEM font_6p = Font<6, 7, 32,96, false, true>({
        "      "
        "      "
        "      "
        "      "
        "      "
        "      "
        "      ",
        "x     "
        "x     "
        "x     "
        "x     "
        "      "
        "x     "
        "      ",
        "x x   "
        "x x   "
        "      "
        "      "
        "      "
        "      "
        "      ",
        "      "
        " x x  "
        "xxxxx "
        " x x  "
        "xxxxx "
        " x x  "
        "      ",
        "  x   "
        "xxxxx "
        "x x   "
        "xxxxx "
        "  x x "
        "xxxxx "
        "  x   ",
        "xx    "
         "xx  x "
         "   x  "
         "  x   "
         " x    "
         "x  xx "
         "   xx ",
        " x    "
        "x x   "
        "x x   "
        " xx x "
        "x  x  "
        "xxx x "
        "      ",
        "x     "
        "x     "
        "      "
        "      "
        "      "
        "      "
        "      ",
        " x    "
        "x     "
        "x     "
        "x     "
        "x     "
        " x    "
        "      ",
        "x     "
        " x    "
        " x    "
        " x    "
        " x    "
        "x     "
        "      ",
        "      "
        " x x  "
        "  x   "
        "xxxxx "
        "  x   "
        " x x  "
        "      ",
        "      "
        "      "
        " x    "
        "xxx   "
        " x    "
        "      "
        "      ",
        "      "
        "      "
        "      "
        "      "
        " x    "
        " x    "
        "x     ",
        "      "
        "      "
        "      "
        "xxx   "
        "      "
        "      "
        "      ",
        "      "
        "      "
        "      "
        "      "
        "      "
        "x     "
        "      ",
        "  x   "
        "  x   "
        " x    "
        " x    "
        "x     "
        "x     "
        "      ",
        " xx   "
        "x  x  "
        "x  x  "
        "x  x  "
        "x  x  "
        " xx   "
        "      ",
        "  x   "
        " xx   "
        "x x   "
        "  x   "
        "  x   "
        "  x   "
        "      ",
        " xx   "
        "x  x  "
        "   x  "
        " xx   "
        "x     "
        "xxxx  "
        "      ",
        " xx   "
        "x  x  "
        "  x   "
        "   x  "
        "x  x  "
        " xx   "
        "      ",
        "  x   "
        " xx   "
        "x x   "
        "xxxx  "
        "  x   "
        "  x   "
        "      ",
        "xxxx  "
        "x     "
        "xxx   "
        "   x  "
        "x  x  "
        " xx   "
        "      ",
        " xx   "
        "x     "
        "xxx   "
        "x  x  "
        "x  x  "
        " xx   "
        "      ",
        "xxxx  "
        "   x  "
        "  x   "
        "  x   "
        " x    "
        " x    "
        "      ",
        " xx   "
        "x  x  "
        " xx   "
        "x  x  "
        "x  x  "
        " xx   "
        "      ",
        " xx   "
        "x  x  "
        "x  x  "
        " xxx  "
        "   x  "
        " xx   "
        "      ",
        "      "
        "      "
        "      "
        "x     "
        "      "
        "x     "
        "      ",
        "      "
        "      "
        "      "
        " x    "
        "      "
        " x    "
        "x     ",
        "      "
        "  x   "
        " x    "
        "x     "
        " x    "
        "  x   "
        "      ",
        "      "
        "      "
        "xxx   "
        "      "
        "xxx   "
        "      "
        "      ",
        "      "
        "x     "
        " x    "
        "  x   "
        " x    "
        "x     "
        "      ",
        " xx   "
        "x  x  "
        "   x  "
        "  x   "
        "      "
        "  x   "
        "      ",
        "  xxx "
        " x   x"
        "x  x x"
        "x x xx"
        "x  x x"
        " x    "
        "  xxxx",
        " xx   "
        "x  x  "
        "x  x  "
        "xxxx  "
        "x  x  "
        "x  x  "
        "      ",
        "xxx   "
        "x  x  "
        "xxx   "
        "x  x  "
        "x  x  "
        "xxx   "
        "      ",
        " xx   "
        "x  x  "
        "x     "
        "x     "
        "x  x  "
        " xx   "
        "      ",
        "xx    "
        "x x   "
        "x  x  "
        "x  x  "
        "x x   "
        "xx    "
        "      ",
        "xxxx  "
        "x     "
        "xx    "
        "x     "
        "x     "
        "xxxx  "
        "      ",
        "xxxx  "
        "x     "
        "xx    "
        "x     "
        "x     "
        "x     "
        "      ",
        " xx   "
        "x  x  "
        "x     "
        "x xx  "
        "x  x  "
        " xx   "
        "      ",
        "x  x  "
        "x  x  "
        "xxxx  "
        "x  x  "
        "x  x  "
        "x  x  "
        "      ",
        "xxx   "
        " x    "
        " x    "
        " x    "
        " x    "
        "xxx   "
        "      ",
        " xxx  "
        "   x  "
        "   x  "
        "   x  "
        "x  x  "
        " xx   "
        "      ",
        "x  x  "
        "x x   "
        "xx    "
        "x x   "
        "x  x  "
        "x  x  "
        "      ",
        "x     "
        "x     "
        "x     "
        "x     "
        "x     "
        "xxxx  "
        "      ",
        "x   x "
        "xx xx "
        "x x x "
        "x   x "
        "x   x "
        "x   x "
        "      ",
        "x  x  "
        "xx x  "
        "xx x  "
        "x xx  "
        "x xx  "
        "x  x  "
        "      ",
        " xx   "
        "x  x  "
        "x  x  "
        "x  x  "
        "x  x  "
        " xx   "
        "      ",
        "xxx   "
        "x  x  "
        "x  x  "
        "xxx   "
        "x     "
        "x     "
        "      ",
        " xx   "
        "x  x  "
        "x  x  "
        "x  x  "
        "x xx  "
        " xxx  "
        "      ",
        "xxx   "
        "x  x  "
        "x  x  "
        "xxx   "
        "x  x  "
        "x  x  "
        "      ",
        " xx   "
        "x     "
        " xx   "
        "   x  "
        "x  x  "
        " xx   "
        "      ",
        "xxxxx "
        "  x   "
        "  x   "
        "  x   "
        "  x   "
        "  x   "
        "      ",
        "x  x  "
        "x  x  "
        "x  x  "
        "x  x  "
        "x  x  "
        " xx   "
        "      ",
        "x   x "
        "x   x "
        "x   x "
        "x   x "
        " x x  "
        "  x   "
        "      ",
        "x   x "
        "x   x "
        "x   x "
        "x x x "
        "x x x "
        " x x  "
        "      ",
        "x   x "
        " x x  "
        "  x   "
        " x x  "
        "x   x "
        "x   x "
        "      ",
        "x   x "
        "x   x "
        " x x  "
        "  x   "
        "  x   "
        "  x   "
        "      ",
        "xxxx  "
        "   x  "
        "  x   "
        " x    "
        "x     "
        "xxxx  "
        "      ",
        "xx    "
        "x     "
        "x     "
        "x     "
        "x     "
        "xx    "
        "      ",
        "      "
        "x     "
        " x    "
        "  x   "
        "   x  "
        "      "
        "      ",
        "xx    "
        " x    "
        " x    "
        " x    "
        " x    "
        "xx    "
        "      ",
        "  x   "
        " xxx  "
        "x x x "
        "  x   "
        "  x   "
        "  x   "
        "      ",
        "      "
        "      "
        "      "
        "      "
        "      "
        "      "
        "xxxxx ",
        "x     "
        " x    "
        "      "
        "      "
        "      "
        "      "
        "      ",
        "      "
        "      "
        " xx   "
        "  xx  "
        "xx x  "
        " xxx  "
        "      ",
        "x     "
        "x     "
        "xxx   "
        "x  x  "
        "x  x  "
        "xxx   "
        "      ",
        "      "
        "      "
        " xxx  "
        "x     "
        "x     "
        " xxx  "
        "      ",
        "   x  "
        "   x  "
        " xxx  "
        "x  x  "
        "x  x  "
        " xxx  "
        "      ",
        "      "
        "      "
        " xx   "
        "x xx  "
        "xx    "
        " xxx  "
        "      ",
        "  x   "
        " x    "
        "xxx   "
        " x    "
        " x    "
        " x    "
        "      ",
        "      "
        "      "
        " xxx  "
        "x  x  "
        " xxx  "
        "   x  "
        " xx   ",
        "x     "
        "x     "
        "xxx   "
        "x  x  "
        "x  x  "
        "x  x  "
        "      ",
        " x    "
        "      "
        "xx    "
        " x    "
        " x    "
        "xxx   "
        "      ",
        "  x   "
        "      "
        " xx   "
        "  x   "
        "  x   "
        "  x   "
        "xx    ",
        "x     "
        "x     "
        "x x   "
        "xx    "
        "x x   "
        "x  x  "
        "      ",
        "x     "
        "x     "
        "x     "
        "x     "
        "x     "
        " x    "
        "      ",
        "      "
        "      "
        "xxxx  "
        "x x x "
        "x x x "
        "x x x "
        "      ",
        "      "
        "      "
        "xxx   "
        "x  x  "
        "x  x  "
        "x  x  "
        "      ",
        "      "
        "      "
        " xx   "
        "x  x  "
        "x  x  "
        " xx   "
        "      ",
        "      "
        "      "
        "xxx   "
        "x  x  "
        "xxx   "
        "x     "
        "x     ",
        "      "
        "      "
        " xxx  "
        "x  x  "
        " xxx  "
        "   x  "
        "   xx ",
        "      "
        "      "
        " xxx  "
        "x     "
        "x     "
        "x     "
        "      ",
        "      "
        "      "
        " xx   "
        "xx    "
        "  xx  "
        "xxx   "
        "      ",
        " x    "
        "xxx   "
        " x    "
        " x    "
        " x    "
        "  x   "
        "      ",
        "      "
        "      "
        "x  x  "
        "x  x  "
        "x  x  "
        " xx   "
        "      ",
        "      "
        "      "
        "x   x "
        "x   x "
        " x x  "
        "  x   "
        "      ",
        "      "
        "      "
        "x   x "
        "x x x "
        "x x x "
        " x x  "
        "      ",
        "      "
        "      "
        "x  x  "
        " xx   "
        " xx   "
        "x  x  "
        "      ",
        "      "
        "      "
        "x  x  "
        "x  x  "
        " xxx  "
        "   x  "
        " xx   ",
        "      "
        "      "
        "xxxx  "
        "  x   "
        " x    "
        "xxxx  "
        "      ",
        " xx   "
        " x    "
        "xx    "
        " x    "
        " x    "
        " xx   "
        "      ",
        "x     "
        "x     "
        "x     "
        "x     "
        "x     "
        "x     "
        "      ",
        "xx    "
        " x    "
        " xx   "
        " x    "
        " x    "
        "xx    "
        "      ",
        "      "
        " x    "
        "x x x "
        "   x  "
        "      "
        "      "
        "      ",
        "      "
        "  x   "
        "  x   "
        "  x   "
        "x x x "
        " xxx  "
        "  x   "

}, 4);

}
