#pragma once

#include "../includes/font.h"

#ifdef __AVR__
#include <avr/pgmspace.h>
#else
#define PROGMEM
#endif

namespace Matrix_MAX7219 {


constexpr auto PROGMEM font_5x3 = Font<4,6,32,96, true, true> ({
        "    "
        "    "
        "    "
        "    "
        "    "
        "    ",
        " X  "
        " X  "
        " X  "
        "    "
        " X  "
        "    ",
        "X X "
        "X X "
        "    "
        "    "
        "    "
        "    ",
        "X X "
        "XXX "
        "X X "
        "XXX "
        "X X "
        "    ",
        "XXX "
        "XX  "
        "XXX "
        " XX "
        "XXX "
        "    ",
        "X X "
        "  X "
        " X  "
        "X   "
        "X X "
        "    ",
        " O  "
        "O O "
        " O  "
        "O  O"
        "OOO "
        "    ",
        " X  "
        " X  "
        "    "
        "    "
        "    "
        "    ",
        "  X "
        " X  "
        " X  "
        " X  "
        "  X "
        "    ",
        "X   "
        " X  "
        " X  "
        " X  "
        "X   "
        "    ",
        "    "
        "X X "
        " X  "
        "X X "
        "    "
        "    ",
        "    "
        " X  "
        "XXX "
        " X  "
        "    "
        "    ",
        "    "
        "    "
        "    "
        " X  "
        " X  "
        "X   ",
        "    "
        "    "
        "XXX "
        "    "
        "    "
        "    ",
        "    "
        "    "
        "    "
        "    "
        " X  "
        "    ",
        "    "
        "  X "
        " X  "
        "X   "
        "    "
        "    ",
        "XXX "
        "X X "
        "X X "
        "X X "
        "XXX "
        "    ",
        "  X "
        "  X "
        "  X "
        "  X "
        "  X "
        "    ",
        "XXX "
        "  X "
        "XXX "
        "X   "
        "XXX "
        "    ",
        "XXX "
        "  X "
        "XXX "
        "  X "
        "XXX "
        "    ",
        "X X "
        "X X "
        "XXX "
        "  X "
        "  X "
        "    ",
        "XXX "
        "X   "
        "XXX "
        "  X "
        "XXX "
        "    ",
        "XXX "
        "X   "
        "XXX "
        "X X "
        "XXX "
        "    ",
        "XXX "
        "  X "
        "  X "
        "  X "
        "  X "
        "    ",
        "XXX "
        "X X "
        "XXX "
        "X X "
        "XXX "
        "    ",
        "XXX "
        "X X "
        "XXX "
        "  X "
        "XXX "
        "    ",
        "    "
        " X  "
        "    "
        " X  "
        "    "
        "    ",
        "    "
        " X  "
        "    "
        " X  "
        " X  "
        "X   ",
        "  X "
        " X  "
        "X   "
        " X  "
        "  X "
        "    ",
        "    "
        "XXX "
        "    "
        "XXX "
        "    "
        "    ",
        "X   "
        " X  "
        "  X "
        " X  "
        "X   "
        "    ",
        "XX  "
        "  X "
        " X  "
        "    "
        " X  "
        "    ",
        " XX "
        "X  X"
        "XXXX"
        "XX X"
        " XX "
        "    ",
        " X  "
        "X X "
        "XXX "
        "X X "
        "X X "
        "    ",
        "XX  "
        "X X "
        "XX  "
        "X X "
        "XX  "
        "    ",
        " XX "
        "X   "
        "X   "
        "X   "
        " XX "
        "    ",
        "XX  "
        "X X "
        "X X "
        "X X "
        "XX  "
        "    ",
        "XXX "
        "X   "
        "XX  "
        "X   "
        "XXX "
        "    ",
        "XXX "
        "X   "
        "XX  "
        "X   "
        "X   "
        "    ",
        " XX "
        "X   "
        "X X "
        "X X "
        " XX "
        "    ",
        "X X "
        "X X "
        "XXX "
        "X X "
        "X X "
        "    ",
        "XXX "
        " X  "
        " X  "
        " X  "
        "XXX "
        "    ",
        "XXX "
        "  X "
        "  X "
        "X X "
        " X  "
        "    ",
        "X X "
        "X X "
        "XX  "
        "X X "
        "X X "
        "    ",
        "X   "
        "X   "
        "X   "
        "X   "
        "XXX "
        "    ",
        "X X "
        "XXX "
        "XXX "
        "X X "
        "X X "
        "    ",
        "XX  "
        "X X "
        "X X "
        "X X "
        "X X "
        "    ",
        " X  "
        "X X "
        "X X "
        "X X "
        " X  "
        "    ",
        "XX  "
        "X X "
        "XXX "
        "X   "
        "X   "
        "    ",
        " X  "
        "X X "
        "X X "
        "XXX "
        " XX "
        "    ",
        "XX  "
        "X X "
        "XX  "
        "X X "
        "X X "
        "    ",
        " XX "
        "X   "
        " X  "
        "  X "
        "XX  "
        "    ",
        "XXX "
        " X  "
        " X  "
        " X  "
        " X  "
        "    ",
        "X X "
        "X X "
        "X X "
        "X X "
        "XXX "
        "    ",
        "X X "
        "X X "
        "X X "
        "X X "
        " X  "
        "    ",
        "X X "
        "X X "
        "XXX "
        "XXX "
        " X  "
        "    ",
        "X X "
        "X X "
        " X  "
        "X X "
        "X X "
        "    ",
        "X X "
        "X X "
        " X  "
        " X  "
        " X  "
        "    ",
        "XXX "
        "  X "
        " X  "
        "X   "
        "XXX "
        "    ",
        " XX "
        " X  "
        " X  "
        " X  "
        " XX "
        "    ",
        "    "
        "X   "
        " X  "
        "  X "
        "    "
        "    ",
        "XX  "
        " X  "
        " X  "
        " X  "
        "XX  "
        "    ",
        " X  "
        "X X "
        "    "
        "    "
        "    "
        "    ",
        "    "
        "    "
        "    "
        "    "
        "    "
        "XXXX",
        " X  "
        "  X "
        "    "
        "    "
        "    "
        "    ",
        " X  "
        "X X "
        "XXX "
        "X X "
        "X X "
        "    ",
        "XX  "
        "X X "
        "XX  "
        "X X "
        "XX  "
        "    ",
        " XX "
        "X   "
        "X   "
        "X   "
        " XX "
        "    ",
        "XX  "
        "X X "
        "X X "
        "X X "
        "XX  "
        "    ",
        "XXX "
        "X   "
        "XX  "
        "X   "
        "XXX "
        "    ",
        "XXX "
        "X   "
        "XX  "
        "X   "
        "X   "
        "    ",
        " XX "
        "X   "
        "X X "
        "X X "
        " XX "
        "    ",
        "X X "
        "X X "
        "XXX "
        "X X "
        "X X "
        "    ",
        "XXX "
        " X  "
        " X  "
        " X  "
        "XXX "
        "    ",
        "XXX "
        "  X "
        "  X "
        "X X "
        " X  "
        "    ",
        "X X "
        "X X "
        "XX  "
        "X X "
        "X X "
        "    ",
        "X   "
        "X   "
        "X   "
        "X   "
        "XXX "
        "    ",
        "X X "
        "XXX "
        "XXX "
        "X X "
        "X X "
        "    ",
        "XX  "
        "X X "
        "X X "
        "X X "
        "X X "
        "    ",
        " X  "
        "X X "
        "X X "
        "X X "
        " X  "
        "    ",
        "XX  "
        "X X "
        "XXX "
        "X   "
        "X   "
        "    ",
        " X  "
        "X X "
        "X X "
        "XXX "
        " XX "
        "    ",
        "XX  "
        "X X "
        "XX  "
        "X X "
        "X X "
        "    ",
        " XX "
        "X   "
        " X  "
        "  X "
        "XX  "
        "    ",
        "XXX "
        " X  "
        " X  "
        " X  "
        " X  "
        "    ",
        "X X "
        "X X "
        "X X "
        "X X "
        "XXX "
        "    ",
        "X X "
        "X X "
        "X X "
        "X X "
        " X  "
        "    ",
        "X X "
        "X X "
        "XXX "
        "XXX "
        " X  "
        "    ",
        "X X "
        "X X "
        " X  "
        "X X "
        "X X "
        "    ",
        "X X "
        "X X "
        " X  "
        " X  "
        " X  "
        "    ",
        "XXX "
        "  X "
        " X  "
        "X   "
        "XXX "
        "    ",
        " XX "
        " X  "
        "X   "
        " X  "
        " XX "
        "    ",
        " X  "
        " X  "
        " X  "
        " X  "
        " X  "
        "    ",
        "XX  "
        " X  "
        "  X "
        " X  "
        "XX  "
        "    ",
        " X X"
        "X X "
        "    "
        "    "
        "    "
        "    ",
        "  X "
        " X  "
        "XXXX"
        " X  "
        "  X "
        "    ",
});

constexpr auto PROGMEM font_5x3p = Font<4,6,32,96, false, true> (font_5x3, 3);

}
